load("//ReactNative:DEFS.bzl", "rn_android_library", "react_native_dep")

rn_android_library(
    name = "annotations",
    srcs = glob(["*.java"]),
    visibility = [
        "PUBLIC",
    ],
    deps = [
        react_native_dep("third-party/java/jsr-305:jsr-305"),
    ],
)
